mqtt:
  enabled: true
  host: 192.168.60.174
  port: 1883
  user: mqtt-user
  password: juUAT629acn9ZMJK

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

objects:
  track:
    - person
  filters:
    person:
      min_area: 10000

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

snapshots:
  enabled: true
  retain:
    default: 30

go2rtc:
  streams:
    cam101:
      - rtsp://admin:827gYwh92jhZ@192.168.60.93:554/stream0:0
      - ffmpeg:cam101#audio=aac
  webrtc:
    listen: :8555    # address of your local server and port (TCP/UDP)
    candidates:
      - stun:8555  # if you have a dynamic public IP address
      - 192.168.60.220:8555

cameras:
  cam101:
    detect:
      width: 1280
      height: 720
      fps: 7
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/cam101 # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

    #motion:
      #mask:
        #- 0.000,0.427,0.002,0.000,0.999,0.000,0.999,0.781,0.885,0.456,0.700,0.424,0.701,0.311,0.507,0.294,0.453,0.347,0.451,0.400
detect:
  enabled: true
version: 0.16-0
semantic_search:
  enabled: false
  model_size: large
face_recognition:
  enabled: true
  model_size: large
lpr:
  enabled: false
classification:
  bird:
    enabled: false
